name: BedAdditions
version: 2.0
main: me.bedpotato.bedadditions.BedAdditions
api-version: 1.17
authors: [ BedPotato ]
description: Features provided to Mytheus by BedPotato
commands:
  ba:
    description: default command